#######################################################################
#
#                         BugBlockFix
#            修复AAC和部分小游戏插件不兼容造成的无敌方块BUG
#                          作者: RE
#
#######################################################################
# MCBBS: jebme
# QQ: 1609403959

#注入设定
inject:

  # 注入方法位置
  # 格式: 完整类名:方法名字
  # 例如: net.xxxxxx.listener.BlockListener:onPlace
  methods:
    # 起床战争 1.3.6 方块监听器
    - 'io.github.bedwarsrel.listener.BlockListener:onBreak'

  # 优先级修改为
  priority: MONITOR

  # 傻瓜式注入,直接注入整个插件
  # 只需填写插件名字，即可自动寻找 对应监听器 实现注入
  # 不推荐 !!!! 使用该功能，如果你 实在 不能理解上面的配置，那就用这个功能吧
  plugins:
    # 默认使用上面的完整路径注入,注释掉了该傻瓜式注入插件列表
    #- 'BedwarsRel'